nelmio_cors:
  paths:
    "^/api/":
      origin_regex: true
      allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
      allow_headers: ["Content-Type"]
      allow_methods: ["GET", "POST"]
      max_age: 3600
